apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-runner
  namespace: drone

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: drone-runner
  namespace: drone
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - create
      - delete
      - list
      - watch
      - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drone-runner
  namespace: drone
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: drone-runner
subjects:
  - kind: ServiceAccount
    name: drone-runner
    namespace: drone

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-runner
  namespace: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-runner
  template:
    metadata:
      labels:
        app: drone-runner
    spec:
      serviceAccountName: drone-runner
      containers:
        - name: drone-runner
          image: drone/drone-runner-kube
          env:
            - name: DRONE_RPC_SECRET
              value: d507a8a7d515f343a6f9caed4f370883
            - name: DRONE_RPC_HOST
              value: drone.pipeline.localhost
            - name: DRONE_RPC_PROTO
              value: http
            - name: DRONE_DEBUG
              value: "true"
            - name: DRONE_NAMESPACE_DEFAULT
              value: drone
            - name: DRONE_SERVICE_ACCOUNT_DEFAULT
              value: drone-runner-pipeline
      hostAliases:
        - ip: 172.21.0.2
          hostnames:
            - drone.pipeline.localhost

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-runner-pipeline
  namespace: drone

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drone-runner-pipeline
  namespace: drone
rules:

  - apiGroups:
      - ""
    resources:
      - namespaces
      - services
      - pods
      - configmaps
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch

  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - create
      - delete
      - list
      - get
      - patch
      - watch

  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - list
      - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: drone-runner-pipeline
  namespace: drone
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: drone-runner-pipeline
subjects:
  - kind: ServiceAccount
    name: drone-runner-pipeline
    namespace: drone
