apiVersion: v1
kind: Namespace
metadata:
  name: gitea

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea
  namespace: gitea
spec:
  rules:
    - host: gitea.src.control.localhost
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: gitea
                port:
                  name: http

---

apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: gitea
spec:
  selector:
    app: gitea
  ports:
    - name: http
      port: 80
      targetPort: http

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: docker.gitea.com/gitea:1.24.6-rootless
          env:
            - name: GITEA__webhook__ALLOWED_HOST_LIST
              value: drone.pipeline.localhost
            - name: GITEA__webhook__SKIP_TLS_VERIFY
              value: "true"
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /var/lib/gitea
            - name: config
              mountPath: /etc/gitea
      hostAliases:
        - ip: 172.21.0.2
          hostnames:
            - drone.pipeline.localhost
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1G
    - metadata:
        name: config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1G
