apiVersion: v1
kind: Namespace
metadata:
  name: http-simple

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-simple
  namespace: http-simple
spec:
  rules:
    - host: http-simple.api.localhost
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: http-simple
                port:
                  name: http

---

apiVersion: v1
kind: Service
metadata:
  name: http-simple
  namespace: http-simple
spec:
  selector:
    app: http-simple
  ports:
    - name: http
      port: 80
      targetPort: http

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: http-simple-env
  namespace: http-simple
data:
  HTTP_SIMPLE_SERVER_PORT: "3000"
  HTTP_SIMPLE_TEST: "foobar"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: http-simple-certificate
  namespace: http-simple
data:
  certificate.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDXzCCAkegAwIBAgILBAAAAAABIVhTCKIwDQYJKoZIhvcNAQELBQAwTDEgMB4G
    A1UECxMXR2xvYmFsU2lnbiBSb290IENBIC0gUjMxEzARBgNVBAoTCkdsb2JhbFNp
    -----END CERTIFICATE-----

---

apiVersion: v1
kind: Secret
metadata:
  name: http-simple-key
  namespace: http-simple
data:
  key.pem: QUJDMTIzCg==

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-simple
  namespace: http-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-simple
  template:
    metadata:
      labels:
        app: http-simple
    spec:
      containers:
        - name: http-simple
          image: local-registry:5000/http-simple:latest
          envFrom:
            - configMapRef:
                name: http-simple-env
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: certificate
              mountPath: /etc/ssl/certs/http-simple
            - name: key
              mountPath: /etc/sss/keys/http-simple
      volumes:
        - name: certificate
          configMap:
            name: http-simple-certificate
        - name: key
          secret:
            secretName: http-simple-key
